version: "3"
services:
  server:
    build: server
    container_name: server
    tty: true
    ports:
      - 5000:5000
  bff:
    build: bff
    container_name: bff
    tty: true
    ports:
      - 4000:4000
  client:
    build: client
    container_name: client
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/src
